### ISSUE TITLE
Cachelite problem with frontend

### ISSUE THREAD

**Issue by wdebusschere** [symphonists/cachelite#27]
We use Symphony 2.61 and cachelite 1.3.
We use a frontend cms, which is loaded after logging in.
When we are logged in (/data/logged-in-author/author) then there is no caching and everything works perfect.
The problem raises after logging out (post to symphony/logout/), we still get the frontend cms loaded on some pages.. so we need to login again and flush=site in order to have the cache recreated..

Everything works perfect without the cachelite extension, but we really need caching.
Problem happens on localhost and on server, in the logs i see:
[Tue Mar 31 18:06:53.091130 2015] [proxy_fcgi:error] [pid 11550:tid 139803965888256] [client 85.247.208.69:58574] AH01070: Error parsing script headers

It's like if the pages with the if $author to load the cms have this part of the code cached,
but no caching comment.. and when logged in, there is no caching of course.
It's like if after logging out, the page cache is not recreated.. cannot be recreated..

Thank you

**Comment by nitriques** [comment]
> The problem raises after logging out (post to symphony/logout/), we still get the frontend cms loaded on some pages.. so we need to login again and flush=site in order to have the cache recreated..

This is "normal". Cachelite sends HTTP headers that tell the browser to cache things locally. When you log out, the browser reverts back to those and gets a 304 from the server, which confuses things. I've never been able to fix this...

> Everything works perfect without the cachelite extension, but we really need caching.
Problem happens on localhost and on server, in the logs i see:
[Tue Mar 31 18:06:53.091130 2015] [proxy_fcgi:error] [pid 11550:tid 139803965888256] [client 85.247.208.69:58574] AH01070: Error parsing script headers

Never saw this... maybe it's a problem on your setup ? http://serverfault.com/questions/421398/apache-php-fpm-random-error-parsing-script-headers-seg-faults 

>  cannot be recreated..

Hum this is strange. But since I can't reproduce it, I do not know what to do.

**Comment by wdebusschere** [comment]
Nitirques,
Is it normal that the cached file starts with
                       3385847675<!DOCTYPE html>....

?
Thank you

**Comment by wdebusschere** [comment]
Nitriques,
What I don't understand is why:
example:
1. /home/ loads first time + creates cache file
2. login on /home/, browser shows the page without caching
3. logout and browser shows still the logged in version.. while there is a cached version why? how is this possible, i check if logged in, and the author is not logged in, but i get the loggedin version..

thx

**Comment by nitriques** [comment]
> Is it normal that the cached file starts with

Yes it is. It's there to check for data validity: See https://github.com/symphonists/cachelite/blob/master/lib/class.cachelite.php#L793

> logout and browser shows still the logged in version.. while there is a cached version why?

Like I already told you: 

> Cachelite sends HTTP headers that tell the browser to cache things locally. When you log out, the browser reverts back to those and gets a 304 from the server, which confuses things. I've never been able to fix this...

I other words:

1. You get a 200 response, with cache headers.
2. You login and then get a new 200, without cache headers.
3. Somehow, after you log in, since you are requesting a page that has been cached (in step 1), the browser sends the cache header. Then the server responds with a 304 and the browser displays the result gotten from step 2.

> Is it possible to fix.

Maybe! Browser level caching is really hard to get right. Cross-browser level caching is even harder and that's what we are trying to do. If you can find a fix, I would be happy to test it/review it.

BTW, How do you log the user in ? With a post to /symphony/login/ ?

**Comment by wdebusschere** [comment]
Nitriques,
Thank you for the explanation.
Login with a post to /symphony/login/ indeed.

I will dig a bit deeper.. a solution would be to be able to disable caching for the IP's of the author.
Extension is great, and a must for our african visitors/clients


Wannes

**Comment by nitriques** [comment]
> a solution would be to be able to disable caching for the IP's of the author.

I would not do that, especially for Africa. Multiple person can share the same IP.

**Comment by wdebusschere** [comment]
Nitriques,
yes, but better to offer 95% of the visitors caching then 0%.
Now we need to disable caching, because it's confusing for the admin of the website to see cms elements (that don't work) after logging out.

**Comment by nitriques** [comment]
Your call. But I can't accept this as a solution for everybody.

**Comment by wdebusschere** [comment]
of course! 100% right! Contact me on info@e-xperience.be if you want to see the system we use..

**Comment by nitriques** [comment]
What happens if you remove this line

https://github.com/symphonists/cachelite/blob/master/extension.driver.php#L304 ?

**Comment by wdebusschere** [comment]
Same, pages i visited while logged in, still show cms elements after logging out

**Comment by nitriques** [comment]
How do you log out ? Via /symphony/logout/ ?

**Comment by wdebusschere** [comment]
With https://github.com/symphonists/cachelite/blob/master/extension.driver.php#L304 ?
After begin logged-in the pages with a cachefile have the cached version loaded, untill i refresh a few timers they get the cms elements..
Logout is via /symphony/logout/  link..

**Comment by nitriques** [comment]
Hum I am not sure that I fully understand what you are saying

**Comment by wdebusschere** [comment]
With L304 commented:
- After login: the pages have the cached version loaded and not the page with new cms elements :(
- After logout: cached version: OK

Without L304 commented:
- After login: the pages have the cms elements loaded: OK
- After logout: the pages have still the cms elements loaded :(

**Comment by nitriques** [comment]
Wow... This baffles me.

**Comment by nitriques** [comment]
What about removing L304 AND this part of L308

|| str_replace('"', NULL, stripslashes($_SERVER['HTTP_IF_NONE_MATCH'])) == $etag

**Comment by wdebusschere** [comment]
Same problem, after login I need to press F5 several times to get the CMS elements, clicking several times on the page link to refresh doesn't help..

**Comment by nitriques** [comment]
Really weird. Please feel free to try and fit it !

**Comment by nitriques** [comment]
Well I just reproduced the problem. That's a start !

**Comment by wdebusschere** [comment]
:+1:
