### ISSUE TITLE
Table: sym_cachelite_references is 250MB after some days is this normal?

### ISSUE THREAD

**Issue by wdebusschere** [symphonists/cachelite#42]
Symphony 2.7.7
Cachelite 2.1.2

'clean-strategy' => 'cron',

**Comment by nitriques** [comment]
If you do not purge it, yes it is. How often do you run the cron job ?

**Comment by wdebusschere** [comment]
cron job every hour.. but doesn't change nothing.. also running it manually doenst make the size of the db less

**Comment by wdebusschere** [comment]
<img width="1080" alt="screenshot 2019-01-31 at 10 37 15" src="https://user-images.githubusercontent.com/4136426/52048836-39d86e80-2544-11e9-8e74-dd175afa37af.png">

**Comment by wdebusschere** [comment]
<img width="1080" alt="Screenshot 2020-02-05 at 09 27 56" src="https://user-images.githubusercontent.com/4136426/73828804-d8537b80-47f9-11ea-892d-cd3cd33d428d.png">

**Comment by nitriques** [comment]
@wdebusschere DO you have many many pages (url) on that site ? If so, this is expected... In order to be able purge the cache when editing entries, we need to create a different entry for each entry/section used for each url. I do have sites with 2Gb of data in this table.

Also: do you use many query strings ? This also makes the url different, so maybe you are getting a lot cache hit ratio.

Finally, what is your concern ? Is it speed ? Size on disk ?

**Comment by wdebusschere** [comment]
@nitriques  Thanks for the reply. Ok, so big database is normal. This is a problem as we only got 1GB db's. So i have disabled the storing in the database and the cache expires eventually. If some new data gets added or updated we have created a delete all cache button, which is better in our situation, then to have long delays saving and deleting the cache.

**Comment by nitriques** [comment]
The thing is, it is sometime due to some entries being present on ALL pages (like the menus/footer) that will get the data so big. Maybe we should consider "excluding" some section from this behavior.
